# Generated by Django 3.2.9 on 2022-09-04 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 19, 3, 8, 795874), verbose_name='date published'),
        ),
    ]
